# These are supported funding model platforms
github: <GH USERAME>
patreon: bryanjenks # FIXME change this if you have a patreon
custom:
  [
    "https://www.buymeacoffee.com/<GH USERAME>",
    "https://www.paypal.me/<GH USERAME>",
  ]