name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE by @$AUTHOR (#$NUMBER)"
no-changes-template: "- No changes"
categories:
  - title: "🚀 New Features"
    labels: [ "enhancement" ]
  - title: "🐛 Bug Fixes"
<<<<<<< HEAD
    labels: [ "bug" ]
  - title: "🛠️ Maintenance"
    labels: [ "maintenance" ]
  - title: "📖️ Documentation"
    labels: [ "documentation" ]
=======
    labels:
      - "bug"
  - title: "🛠️ Maintenance"
    labels:
      - "maintenance"
  - title: "📝️ Documentation"
    labels:
      - "documentation"
>>>>>>> 9bd17e14e980f24f62ec868613bffb49b6ed4dbb
version-resolver:
  major:
    labels: [ "major" ]
  minor:
    labels: [ "minor" ]
  patch:
    labels: [ "patch" ]
  default: patch
template: |
  $CHANGES
  ## 👨🏼‍💻 Contributors
  $CONTRIBUTORS
