###################################################
#                      Python
###################################################

# os: linux

# branches:
#   only:
#     - master
#     - develop

# sudo: false

# language: python

# matrix:
#   fast_finish: true
#   include:
#   - python: "2.7"
#   - python: "3.4"
#   - python: "3.5"
#   - python: "3.6"
#   - python: "3.7"
#     dist: xenial
#     sudo: true

#   - os: osx
#     language: generic
#     env: PYTHON=2.7.15

#   - os: osx
#     language: generic
#     env: PYTHON=3.4.8

#   - os: osx
#     language: generic
#     env: PYTHON=3.5.5

#   - os: osx
#     language: generic
#     env: PYTHON=3.6.6

#   - os: osx
#     language: generic
#     env: PYTHON=3.7.0

# before_install: |
#   if [ "$TRAVIS_OS_NAME" == "osx" ]; then
#     brew update
#     brew install openssl readline
#     brew outdated pyenv || brew upgrade pyenv
#     brew install pyenv-virtualenv
#     pyenv install $PYTHON
#     export PYENV_VERSION=$PYTHON
#     export PATH="/Users/travis/.pyenv/shims:${PATH}"
#     pyenv-virtualenv venv
#     source venv/bin/activate
#     python --version
#   fi

# install: pip install -r requirements.txt

# script: invoke tests

# after_success: codecov

###################################################
#                       BASH
###################################################
# script:
#   # Fail if any of these files have warnings
#   - shellcheck  -s bash flash
